---
Name: iqimageutilities
---
SilverStripe\Assets\Image:
  extensions:
    - IQnection\ImageUtilities\Assets\ImageUtilities
SilverStripe\Assets\Storage\DBFile:
  extensions:
    - IQnection\ImageUtilities\Assets\ImageUtilities
